apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk199-my-app-python
  namespace: class-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk199-my-app-python
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 03ed93dc
      labels:
        app: sk199-my-app-python
    spec:
      serviceAccountName: default
      containers:
      - name: my-app-python
        image: amdp-registry.skala-ai.com/skala25a/sk199-my-app-python:1.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk199
        - name: NAMESPACE
          value: class-3
