apiVersion: v1
kind: Service
metadata:
  name: sk199-my-app-python
  namespace: class-3
spec:
  selector:
    app: sk199-my-app-python
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


