apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-spring-ai-server
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-spring-ai-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: eceada25
      labels:
        app: mcp-spring-ai-server
    spec:
      serviceAccountName: default
      containers:
      - name: spring-ai-server
        image: amdp-registry.skala-ai.com/skala25a/mcp-spring-ai-server:1.0.0
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: mcp
        - name: NAMESPACE
          value: skala-practice
        - name: SPRING_PROFILES_ACTIVE  
          value: "prod"  
