apiVersion: v1
kind: Service
metadata:
  name: mcp-spring-ai-server
  namespace: skala-practice
spec:
  selector:
    app: mcp-spring-ai-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


