apiVersion: v1
kind: Service
metadata:
  name: sk199-myfirst-api-server
  namespace: class-3
spec:
  selector:
    app: sk199-myfirst-api-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
